#!/usr/bin/env bash

heroku config:set \
    NUM_PROJECTS=2 \
    MIXPANEL_SECRET_0=$MIXPANEL_SECRET_0 \
    MIXPANEL_TOKEN_0=$MIXPANEL_TOKEN_0 \
    MIXPANEL_SECRET_1=$MIXPANEL_SECRET_1 \
    MIXPANEL_TOKEN_1=$MIXPANEL_TOKEN_1 \
